version: "2.4"

services:
  gps-mqtt:
# edit config/mosquitto.conf and password.txt
    image: eclipse-mosquitto
    container_name: gps-mqtt
    restart: unless-stopped
    volumes:
      - ${MQTT_PATH:-.}/config:/mosquitto/config:rw
    ports:
      - 1883:1883
#      - 9001:9001
    networks:
      - mqttnet

  gps-mqtt-bridge:
    container_name: gps-mqtt-bridge
    build:
      context: ${MQTT_PATH:-.}
      dockerfile: dockerfile-mqtt-bridge
    image: gps-mqtt-bridge:latest
    restart: unless-stopped
    depends_on: 
      - gps-mqtt
    environment:
      MQTT_SERVER: gps-mqtt
      MQTT_PORT: 1883
      MQTT_USER: gps
      MQTT_PW: ${MQTT_PW}
      MQTT_TOPIC: owntracks
      TCP_SERVER: example.tld
      TCP_PORT: 20202
      PSK_ENC: ${MQTT_ENC_SECRET}
    networks:
      - mqttnet

networks:
   mqttnet:
     driver: bridge

