ARG NGINX_TAG
FROM nginx:$NGINX_TAG
ARG HTML_PATH
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY  --chown=www-data:www-data $HTML_PATH /var/www/html
RUN rm -rf /var/www/html/db && \
    rm -rf /var/www/html/temp && \
    chmod -R u=rwx,g=rx,o= /var/www/html && \
    usermod -a -G www-data nginx 
